"""add nail_types and design_tiers, rework appointments

Revision ID: fe36bbe93579
Revises: df7d1ac1f4cc
Create Date: 2026-08-05 15:28:28.181862

"""
from typing import Sequence, Union
import uuid
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe36bbe93579'
down_revision: Union[str, Sequence[str], None] = 'df7d1ac1f4cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    design_tiers = op.create_table('design_tiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    nail_types = op.create_table('nail_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    # Seed the 3 nail types and 3 design tiers (owner can adjust prices/durations later)
    now = datetime.now(timezone.utc)

    def _row(name, price, duration, order):
        return {
            "id": uuid.uuid4(), "name": name, "price": price,
            "duration_minutes": duration, "sort_order": order, "is_active": True,
            "created_at": now, "updated_at": now,
        }

    op.bulk_insert(nail_types, [
        _row("Short", 30, 60, 1),
        _row("Regular", 40, 75, 2),
        _row("Extensions", 55, 120, 3),
    ])
    op.bulk_insert(design_tiers, [
        _row("Simple", 10, 15, 1),
        _row("Medium", 25, 45, 2),
        _row("Advanced", 45, 90, 3),
    ])

    # service_id is being replaced with no valid mapping to the new schema.
    # Clear existing appointments so the non-nullable FK columns can be added.
    op.execute("DELETE FROM appointments")

    op.add_column('appointments', sa.Column('nail_type_id', sa.Uuid(), nullable=False))
    op.add_column('appointments', sa.Column('design_tier_id', sa.Uuid(), nullable=False))
    op.add_column('appointments', sa.Column('quoted_price', sa.Numeric(precision=8, scale=2), nullable=False))
    op.add_column('appointments', sa.Column('ai_confidence', sa.String(length=20), nullable=True))
    op.add_column('appointments', sa.Column('ai_reasoning', sa.String(length=1000), nullable=True))
    op.drop_constraint(op.f('appointments_service_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'nail_types', ['nail_type_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'design_tiers', ['design_tier_id'], ['id'])
    op.drop_column('appointments', 'service_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('service_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_service_id_fkey'), 'appointments', 'services', ['service_id'], ['id'])
    op.drop_column('appointments', 'ai_reasoning')
    op.drop_column('appointments', 'ai_confidence')
    op.drop_column('appointments', 'quoted_price')
    op.drop_column('appointments', 'design_tier_id')
    op.drop_column('appointments', 'nail_type_id')
    op.drop_table('nail_types')
    op.drop_table('design_tiers')
    # ### end Alembic commands ###
